GLIDEDIR=/usr/local/glide/lib
MESAINCLUDEDIR=/usr/include/GL
MESALIBDIR=/usr/lib

CC = g++-2.95
CXX = g++-2.95
LD = g++-2.95
#PROFILE_FLAGS = -pg
PROFILE_FLAGS =
DEBUG = -O3 -DNDEBUG
#DEBUG = -g 

L3D_LIBS = -L$(CURRENT_PATH_TO_APP_BIN)/lib -l3d -ldl -lm
MESA_LIBS = -L$(MESALIBDIR) -lglut -lGLU -lGL
X_LIBS = -L/usr/X11R6/lib -lXt -lXi -lXmu -lXext -lX11
#GLIDE_LIBS = -L$(GLIDEDIR) -lglide2x

LIBS = $(L3D_LIBS) $(GLIDE_LIBS) $(MESA_LIBS) $(X_LIBS) $(PROFILE_FLAGS)
