// L3D realtime 3D library, explained in book "Linux 3D Graphics Programming"
// Copyright (C) 2000  Norman Lin
// Contact: nlin@linux3dgraphicsprogramming.org (alt. nlin@geocities.com)
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License along
// with this program; if not, write to the Free Software Foundation, Inc.,
// 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.

// generated 2000/8/4 17:28:52 CEST by nlingfx@geri.
// using glademm V0.5.9
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/nlingfx/lib3d.C085/source/utils/blendat/blend_at.glade
// for gtk 1.2.8 and gtkmm 1.2.1
//
// Please modify the corresponding derived classes in ./src/dlg_preferences.cc

// we do not yet fully support gettext
#define _N(x) x
#define N_(x) x
#define _(x) x

#include "dlg_preferences.hh"

Dlg_preferences_Glade::Dlg_preferences_Glade(
)
{   dlg_preferences = this;
  btn_preferences_ok = new Gtk::Button("OK");
  btn_preferences_cancel = new Gtk::Button("Cancel");
  btn_saveprefs = new Gtk::Button("Save Preferences");
  hbox1 = new Gtk::HBox(false, 0);
  label14 = new Gtk::Label("Blender working directory");
  entry_blender_working_dir = new Gtk::Entry();
  label15 = new Gtk::Label("Blender workfile");
  entry_blender_workfile = new Gtk::Entry();
  label16 = new Gtk::Label("Attribute database directory");
  entry_attrib_dir = new Gtk::Entry();
  label17 = new Gtk::Label("OID filename");
  entry_oid_filename = new Gtk::Entry();
  btn_find_blender_win = new Gtk::Button("Find Blender Window");
  table2 = new Gtk::Table(5, 2, false);
  btn_preferences_ok->set_name("btn_preferences_ok");
  btn_preferences_ok->set_border_width(4);
  btn_preferences_ok->clicked.connect(SigC::slot((Dlg_preferences*)this, &Dlg_preferences::on_btn_preferences_ok_clicked));
  btn_preferences_cancel->set_name("btn_preferences_cancel");
  btn_preferences_cancel->set_border_width(4);
  btn_preferences_cancel->clicked.connect(SigC::slot((Dlg_preferences*)this, &Dlg_preferences::on_btn_preferences_cancel_clicked));
  btn_saveprefs->set_name("btn_saveprefs");
  _tooltips.set_tip(*btn_saveprefs, "Preferences will be saved to file .blend_at.config", "");
  btn_saveprefs->set_border_width(4);
  btn_saveprefs->clicked.connect(SigC::slot((Dlg_preferences*)this, &Dlg_preferences::on_btn_saveprefs_clicked));
  hbox1->set_name("hbox1");
  hbox1->pack_start(*btn_preferences_ok, false, false, 0);
  hbox1->pack_start(*btn_preferences_cancel, false, false, 0);
  hbox1->pack_start(*btn_saveprefs, false, false, 0);
  dlg_preferences->get_action_area()->set_name("dialog-action_area1");
  dlg_preferences->get_action_area()->set_border_width(10);
  dlg_preferences->get_action_area()->pack_start(*hbox1);
  label14->set_name("label14");
  label14->set_alignment(0.5, 0.5);
  label14->set_padding(0, 0);
  entry_blender_working_dir->set_name("entry_blender_working_dir");
  entry_blender_working_dir->set_editable(true);
  label15->set_name("label15");
  label15->set_alignment(0.5, 0.5);
  label15->set_padding(0, 0);
  entry_blender_workfile->set_name("entry_blender_workfile");
  entry_blender_workfile->set_editable(true);
  label16->set_name("label16");
  label16->set_alignment(0.5, 0.5);
  label16->set_padding(0, 0);
  entry_attrib_dir->set_name("entry_attrib_dir");
  entry_attrib_dir->set_editable(true);
  label17->set_name("label17");
  label17->set_alignment(0.5, 0.5);
  label17->set_padding(0, 0);
  entry_oid_filename->set_name("entry_oid_filename");
  entry_oid_filename->set_editable(true);
  btn_find_blender_win->set_name("btn_find_blender_win");
  btn_find_blender_win->clicked.connect(SigC::slot((Dlg_preferences*)this, &Dlg_preferences::on_btn_find_blender_win_clicked));
  table2->set_name("table2");
  table2->set_border_width(10);
  table2->set_row_spacings(4);
  table2->set_col_spacings(8);
  table2->attach(*label14, 0, 1, 1, 2, 0, 0, 0, 0);
  table2->attach(*entry_blender_working_dir, 1, 2, 1, 2, GTK_EXPAND|GTK_FILL, 0, 0, 0);
  table2->attach(*label15, 0, 1, 2, 3, 0, 0, 0, 0);
  table2->attach(*entry_blender_workfile, 1, 2, 2, 3, GTK_EXPAND|GTK_FILL, 0, 0, 0);
  table2->attach(*label16, 0, 1, 3, 4, 0, 0, 0, 0);
  table2->attach(*entry_attrib_dir, 1, 2, 3, 4, GTK_EXPAND|GTK_FILL, 0, 0, 0);
  table2->attach(*label17, 0, 1, 4, 5, 0, 0, 0, 0);
  table2->attach(*entry_oid_filename, 1, 2, 4, 5, GTK_EXPAND|GTK_FILL, 0, 0, 0);
  table2->attach(*btn_find_blender_win, 0, 1, 0, 1, 0, 0, 0, 0);
  dlg_preferences->get_vbox()->set_name("dialog-vbox1");
  dlg_preferences->get_vbox()->pack_start(*table2);
  dlg_preferences->set_name("dlg_preferences");
  dlg_preferences->set_title("Preferences");
  dlg_preferences->set_position(GTK_WIN_POS_CENTER);
  dlg_preferences->set_policy(true, true, false);
  dlg_preferences->focus_in_event.connect(SigC::slot((Dlg_preferences*)this, &Dlg_preferences::on_dlg_preferences_focus_in_event));
  btn_preferences_ok->show();
  btn_preferences_cancel->show();
  btn_saveprefs->show();
  hbox1->show();
  label14->show();
  entry_blender_working_dir->show();
  label15->show();
  entry_blender_workfile->show();
  label16->show();
  entry_attrib_dir->show();
  label17->show();
  entry_oid_filename->show();
  btn_find_blender_win->show();
  table2->show();
}

Dlg_preferences_Glade::~Dlg_preferences_Glade()
{   delete btn_preferences_ok;
  delete btn_preferences_cancel;
  delete btn_saveprefs;
  delete hbox1;
  delete label14;
  delete entry_blender_working_dir;
  delete label15;
  delete entry_blender_workfile;
  delete label16;
  delete entry_attrib_dir;
  delete label17;
  delete entry_oid_filename;
  delete btn_find_blender_win;
  delete table2;
}
