// generated 2000/8/4 17:28:52 CEST by nlingfx@geri.
// using glademm V0.5.9
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- /home/nlingfx/lib3d.C085/source/utils/blendat/blend_at.glade
// for gtk 1.2.8 and gtkmm 1.2.1
//
// Please modify the corresponding derived classes in ./src/dlg_preferences.hh and./src/dlg_preferences.cc

#ifndef _DLG_PREFERENCES_GLADE_HH
#  define _DLG_PREFERENCES_GLADE_HH

#include <gtk--/dialog.h>
#include <gtk--/tooltips.h>
#include <gtk--/accelgroup.h>
#include <gtk--/button.h>
#include <gtk--/box.h>
#include <gtk--/label.h>
#include <gtk--/entry.h>
#include <gtk--/table.h>

class Dlg_preferences_Glade : public Gtk::Dialog
{   
        
        Gtk::Tooltips _tooltips;
        Gtk::Dialog *dlg_preferences;
        Gtk::Button *btn_preferences_ok;
        Gtk::Button *btn_preferences_cancel;
        Gtk::Button *btn_saveprefs;
        Gtk::HBox *hbox1;
        Gtk::Label *label14;
protected:
        Gtk::Entry *entry_blender_working_dir;
private:
        Gtk::Label *label15;
protected:
        Gtk::Entry *entry_blender_workfile;
private:
        Gtk::Label *label16;
protected:
        Gtk::Entry *entry_attrib_dir;
private:
        Gtk::Label *label17;
protected:
        Gtk::Entry *entry_oid_filename;
        Gtk::Button *btn_find_blender_win;
private:
        Gtk::Table *table2;
protected:
        
        Dlg_preferences_Glade();
        
        ~Dlg_preferences_Glade();
};
#endif
