// generated 2000/8/4 17:28:52 CEST by nlingfx@geri.
// using glademm V0.5.9
//
// some glademm convenience functions
//
// DO NOT EDIT THIS FILE !

#ifndef GLADEMM_SUPPORT_HH
#define GLADEMM_SUPPORT_HH
#include <string>
#include <map>
#include <gtk--/widget.h>

Gtk::Widget * glademm_get_Widget(const string &name);
void glademm_set_Widget(const string &name, Gtk::Widget *w);

template <class T> T * glademm_get(const string &name)
{   return reinterpret_cast<T*>(glademm_get_Widget(name));
   // 2do: testen ... geht aber nicht ohne Methode gleichen Namens
}
#endif /* GLADEMM_SUPPORT_HH */
